# Generated by Django 2.1.5 on 2019-02-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
