# Generated by Django 2.1.5 on 2019-02-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190209_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='started_date',
            field=models.DateTimeField(),
        ),
    ]
