# Generated by Django 2.1.5 on 2019-03-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customusers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='image',
        ),
    ]
