# Generated by Django 2.1.5 on 2019-05-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_post_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='compound',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='mental_health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='neg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='neutral',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='pos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='strength',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='weight_loss',
            field=models.BooleanField(default=False),
        ),
    ]
